### PR TITLE
Add Swift Package Manager Support

### PR DESCRIPTION
**Pull request by levi**
Moves source files into `Sources` directory at the root of the project and introduces a Package.swift manifest file for Swift Package Manager to manage the framework as a dependency.

### CODE REVIEW

**Comment by jordanebelanger** [comment]
nice

**Comment by jordanebelanger** [comment]
@levi Seems like a .ds_store file was added by accident. Could you update the .gitignore file to ignore those and delete the one that was added please.

**Comment by jordanebelanger** [comment]
I don't have much time to test this, but since this is just moving files around a bit, could you confirm that you did some testing to see if using the library with cocoapods still works fine? @levi

**Comment by levi** [comment]
@jordanebelanger do you have an example app handy I can use to test?

**Comment by jordanebelanger** [comment]
I'm afraid not, I really haven't had much time to work on this recently. Perhaps just a quick single view application with a podfile that has this library rigged to use this PR branch. Just gotta make sure that the SwiftyBluetooth target imports correctly with Cocoapods and SPM and that you can call the functions as per usual, i.e just one successful attempt at calling say, scan for devices, should be enough to confirm.

**Comment by jordanebelanger** [comment]
@levi Just tested with a quick mac app with cocoapods, seemed to work good.

**Comment by levi** [comment]
Great, thanks for doing that!

**Review by jordanebelanger — APPROVED** [review]

**Pull request merged**
