### PR TITLE
Added macOS support

### PR DESCRIPTION
**Pull request by petroladkin**
- added macOS project
- added #if/#else/#endif for the difference between iOS and macOS

### CODE REVIEW

**Comment by jakerockland** [comment]
@petroladkin Is this at a point where it is testable? I may not have a chance to look at it *soon* but very much would like having macOS support and happy to test and contribute!

**Comment by petroladkin** [comment]
@jakerockland the last pull request compiled for macOS but doesn't correctly work in some use cases. Now I testing SwiftyBluetooth in our App (commercial and not open source) on macOS and added small features and fixed one bug/crash. In some days I will create a new pull request with fixes.

**Comment by jordanebelanger** [comment]
Your pull request is turning into far more than a macOS support branch, be careful how you split up your work otherwise it will be much harder to review and integrate the branch.

**Comment by jordanebelanger** [comment]
So, I see at least 3 separate things you are doing right now:

- Mac support
- Running bluetooth tasks on a background queue 
- Cosmetic API changes

I don't have the time to review, test and integrate a branch that implements that many things at once. 

Break them apart into their own separate branch otherwise I won't bother.

**Comment by petroladkin** [comment]
I close this pull request because I will create separated branches for pulls:
- mac support
- support custom work queue
- cosmetic API changes
In my main branch, I will want to apply from separated branches for supporting all features in our project over CocoaPods

**Comment by jordanebelanger** [comment]
Excellent, thank you for your interested in the library.

**Pull request closed without merging**
