### PR TITLE
Swift 5 & Fix warnings

### PR DESCRIPTION
**Pull request by emrcftci**
# Description

 - This pull-request contains Swift version update & warning fixes

# Motivation and Context

 - We'll have latest Swift version,

 - We'll solve language version related warnings

 after this pull-request merge.

# What kind of change does this PR introduce?

- [x] Bug fix (non-breaking change which fixes an issue)
- [x] File changes for improvement
- [ ] New feature (non-breaking change which adds functionality)
- [x] This change requires a documentation update

### CODE REVIEW

**Comment by emrcftci** [comment]
@jordanebelanger thanks for the project! I'm using the library in my projects but I want to avoid warnings. 
PTAL 🚀

**Comment by jordanebelanger** [comment]
Hi @emrcftci 

Thank you for the pull request, very appreciated. I haven't had that much interest on working on this library as I have been working mostly on swift server side stuff and other projects. 

But, I still managed to update this library recently, sort of :) 

Before I check about merging your PR, please check out this branch and test it out, it already includes your changes and more (it uses Swift 5.0's own `Result` type`)
 https://github.com/jordanebelanger/SwiftyBluetooth/tree/2

If it works good for you, I will merge it to master and create a new release, my problem is testing which I haven't had much time to do.

**Comment by jordanebelanger** [comment]
@emrcftci I created a PR for that branch here https://github.com/jordanebelanger/SwiftyBluetooth/pull/43

**Comment by emrcftci** [comment]
Thanks for quick response. Of-course it is good for me 🚀 I'm going to close this pull-request.

**Comment by jordanebelanger** [comment]
@emrcftci Could you test out that branch by any chance? Would appreciate it a lot and help me merge the PR faster.

**Pull request closed without merging**
